cleaned up plot rsync transfer

diff --git a/site-linux/rsync_to_campus b/site-linux/rsync_to_campus
--- a/site-linux/rsync_to_campus
+++ b/site-linux/rsync_to_campus
@@ -42,7 +42,6 @@ else
 fi
 
 readonly PLOTDEST="/home/dataman/antennas_iq_plots/${RADAR_ID}_iq_plots/"
-readonly TEMPDEST="${HOME}/logs/.rsync_partial"
 
 # Create log file. New file created daily
 readonly LOGGING_DIR="${HOME}/logs/rsync_to_campus/$(date +%Y/%m)"
@@ -146,22 +145,28 @@ done
 
 # Find all antennas iq plots to transfer
 files=$(find "${IQPLOT_SOURCE}" -type f -regex ".*\.\(png\|jpg\)")
-if [[ -n ${files} ]]; then
-    # Send each image to remote location and delete locally.
-    for file in $files; do
-        # Get the file name and its directory, then rsync it.
-        image=$(basename $file)
-        path=$(dirname $file)
-        cd $path
-        rsync -av --partial --partial-dir=${TEMPDEST} --timeout=180 --rsh=ssh ${image} $SDCOPY:$PLOTDEST
+for file in $files; do
+  # Get the file name and its directory, then rsync it.
+  image=$(basename $file)
+  path=$(dirname $file)
+  cd $path
 
-        ret=$?
-        if [ ${ret} -eq 0 ]; then
-            echo "Deleting file: ${file}"
-            rm -v ${file}
-        fi
-    done
-fi
+  printf "\nTransferring: ${image}\n"
+  rsync -av --append-verify --timeout=180 --rsh=ssh ${image} $SDCOPY:$PLOTDEST
+
+  # Check if transfer was okay using the md5sum program
+  verify_transfer $file "${PLOTDEST}/${image}" $SDCOPY
+  return_value=$?
+  if [[ $eturn_value -eq 0 ]]; then
+    printf "Successfully transferred: ${image}\n" | tee --append $SUMMARY_FILE
+    printf "Deleting file...\n"
+    rm --verbose ${file}
+  else
+    # If file not transferred successfully, try again next time, don't delete
+    printf "Transfer failed: ${image}\n" | tee --append $SUMMARY_FILE
+    printf "File not deleted.\n"
+  fi
+done
 
 printf "\nFinished $(basename $0). End time: $(date --utc "+%Y%m%d %H:%M:%S UTC")\n\n" | tee --append $SUMMARY_FILE
 
