Refined formatting and logging for distribute_borealis_data

diff --git a/superdarn-cssdp/distribute_borealis_data b/superdarn-cssdp/distribute_borealis_data
--- a/superdarn-cssdp/distribute_borealis_data
+++ b/superdarn-cssdp/distribute_borealis_data
@@ -21,8 +21,23 @@
 # Usage: ./distribute_borealis_data RADAR_ID
 # Parameter RADAR_ID: [sas, pgr, rkn, inv, cly]
 
-readonly RADAR_ID="${1}"
+##############################################################################
 
+# Specify error behaviour
+set -o errexit   # abort on nonzero exitstatus
+set -o nounset   # abort on unbound variable
+set -o pipefail  # don't hide errors within pipes
+
+readonly HOME_DIR="/home/mrcopy"  # ${HOME} doesn't work since script is run by root
+
+# Load in functions
+source "${HOME}/data_flow/library/data_flow_functions.sh"
+
+##############################################################################
+
+readonly RADAR_ID=$1
+
+# Define directories
 readonly SOURCE="/sddata/${RADAR_ID}_data"
 readonly NAS_DIR="/data/borealis_site_data"
 readonly MIRROR_STAGING_DIR="/data/holding/globus"
@@ -30,111 +45,129 @@ readonly BAS_STAGING_DIR="/home/bas/outgoing/${RADAR_ID}"
 readonly VT_STAGING_DIR="/home/vtsd/outgoing/${RADAR_ID}"
 readonly NSSC_STAGING_DIR="/home/nssc/outgoing/${RADAR_ID}"
 
-# Create two separate logs: 
-#   LOG_FILE: File containing all output from this script
-#   SUMMARY_FILE: File for all sites containing only info on errors
-readonly LOGGING_DIR="/home/mrcopy/logs/distribute_data/${RADAR_ID}"
-mkdir --parents --verbose "${LOGGING_DIR}"
-readonly LOG_FILE="${LOGGING_DIR}/$(date -u +%Y-%m).distribute_data_${RADAR_ID}.log"
-readonly SUMMARY_DIR="/home/mrcopy/logs/distribute_data/summary_logs"
-mkdir --parents --verbose "${SUMMARY_DIR}"
-readonly SUMMARY_FILE="${SUMMARY_DIR}/$(date -u +%Y-%m).distribute_data_summary.log"
+# Flag received from rsync_to_nas script to trigger this script
+readonly FLAG_IN="${HOME_DIR}/data_flow/.inotify_watchdir/.rsync_on_campus_flag_${RADAR_ID}"
 
-exec &> "${LOG_FILE}"
+# Location of inotify watch directory for flags on site linux
+readonly FLAG_DEST="${HOME_DIR}/data_flow/.inotify_watchdir"
 
-# Load in functions
-source "${HOME}/data_flow/library/data_flow_functions.sh"
+# Flag sent out to trigger rsync_to_campus script
+readonly FLAG_OUT="${HOME_DIR}/data_flow/.inotify_flags/.distribute_borealis_data_flag_${RADAR_ID}"
 
-# Date in UTC format for logging
-echo "$(date --utc) - ${RADAR_ID}" | tee --append "${SUMMARY_FILE}"
 
-# Ensure that only a single instance of this script runs.
-if pidof -o %PPID -x -- "$(basename -- $0)" > /dev/null; then
-	echo "Error: Script $0 is already running. Exiting..."
-	exit 1
-fi
+# Create log file. New file created daily
+readonly LOGGING_DIR="${HOME_DIR}/logs/distribute_borealis_data/$(date +%Y)/$(date +%m)"
+mkdir --parents --verbose $LOGGING_DIR
+readonly LOGFILE="${LOGGING_DIR}/${RADAR_ID}.$(date +%Y%m%d).distribute_borealis_data.log"
+readonly  SUMMARY_DIR="${HOME_DIR}/logs/distribute_borealis_data/summary/$(date +%Y)/$(date +%m)"
+mkdir --parents --verbose $SUMMARY_DIR
+readonly SUMMARY_FILE="${SUMMARY_DIR}/${RADAR_ID}.$(date -u +%Y%m%d).distribute_summary.log"
+
+##############################################################################
+
+# Redirect all stdout and sterr in this script to $LOGFILE
+exec &> $LOG_FILE
+
+printf "################################################################################\n\n" | tee --append $SUMMARY_FILE
+
+printf "Executing $(basename "$0") on $(hostname)\n" | tee --append $SUMMARY_FILE
+date --utc "+%Y%m%d %H:%M:%S UTC" | tee --append $SUMMARY_FILE
+
+#### TODO: Do we need a file lock? Multiple instances of this script may be
+#### running at same time for each site. Is this okay? Should we prevent this
+#### or add some safety checks?
+# Ensure that only a single instance of this script runs for this site
+# if pidof -o %PPID -x -- "$(basename -- $0) ${RADAR_ID}" > /dev/null; then
+#     echo "Error: Script $0 is already running. Exiting..."
+#     exit 1
+# fi
 
 dmap_files=$(find ${SOURCE} -name "*rawacf.bz2")
 array_files=$(find ${SOURCE} -name "*rawacf.hdf5")
 
 if [[ -n $dmap_files ]]; then
-    echo "Distributing the following dmap files" 
+    printf "\nDistributing the following dmap files:\n" 
     printf '%s\n' "${dmap_files[@]}"
 else
-    echo "No dmap files found to be transferred."
+    printf "\nNo dmap files found to be transferred.\n"
 fi
 
 # Iterate over all dmap files to be transferred
 for file in $dmap_files; do
-    bzip2 --test "${file}"
+    bzip2 --test $file
     if [[ $? -eq 2 ]]; then
-        echo "DMAP file failed bzip2 test: ${file}" | tee --append "${SUMMARY_FILE}"
+        printf "\nDMAP file failed bzip2 test: ${file}\n" | tee --append $SUMMARY_FILE
         # TODO: Set a flag to notify
     else
-        echo "\nDistributing ${file}"
-        chmod --verbose 664 "${file}"
+        printf "\nDistributing ${file}\n"
+        chmod --verbose 664 $file
 
         # TODO: Do we want to do rsync here instead?
         # TODO: Review changing of groups and permissions differring across destinations
 
-        # Flag will be > 0 if any transfers fail
+        # Flag will be > 0 if any transfers fail since verify_transfer
+        # returns 1 for failed transfer
         transfer_flag=0
 
         # Place file in vtsd outgoing
         cp --preserve --verbose "${file}" "${VT_STAGING_DIR}/"
         chgrp --verbose sddata "${VT_STAGING_DIR}/${file}"   
         verify_transfer "${file}" "${VT_STAGING_DIR}/${file}" 
-        transfer_flag=$((${transfer_flag} + $?))
+        return_value=$?
+        transfer_flag=$(($transfer_flag + $return_value))
 
         # Place file in BAS outgoing
         cp --preserve --verbose "${file}" "${BAS_STAGING_DIR}/"
         chgrp --verbose sddata "${BAS_STAGING_DIR}/${file}"
         verify_transfer "${file}" "${BAS_STAGING_DIR}/${file}"
-        transfer_flag=$((${transfer_flag} + $?))
-        
+        return_value=$?
+        transfer_flag=$(($transfer_flag + $return_value))
+
         # Place file in NSSC outgoing - Uncommment this when NSSC is ready
         # cp --preserve --verbose "${file}" "${NSSC_STAGING_DIR}/"
         # chgrp --verbose sddata "${NSSC_STAGING_DIR}/${file}"
         # verify_transfer "${file}" "${NSSC_STAGING_DIR}/${file}"
-        # transfer_flag=$((${transfer_flag} + $?))
+        return_value=$?
+        transfer_flag=$(($transfer_flag + $return_value))
 
         # Copy for staging to the mirror
-        cp --preserve --verbose "${file}" "${MIRROR_STAGING_DIR}"
+        cp --preserve --verbose "${file}" "${MIRROR_STAGING_DIR}/"
         verify_transfer "${file}" "${MIRROR_STAGING_DIR}/${file}"
-        transfer_flag=$((${transfer_flag} + $?))
-
-        # Move file to campus NAS for long term storage
-        year=$(echo ${file} | cut -c 1-4)
-        month=$(echo ${file} | cut -c 5-6)
-        nas_site_dir="${NAS_DIR}/${RADAR_ID}_rawacf_dmap/${year}/${month}/"
-        mkdir --parents "${nas_site_dir}"
-        mv --verbose "${file}" "${nas_site_dir}"
+        return_value=$?
+        transfer_flag=$(($transfer_flag + $return_value))
 
         # Check that all files were copied successfully
+        # If any transfers failed, leave file in directory so tranfer
+        # can be attempted the next time the script runs
         if [[ "${transfer_flag}" -ge 0 ]]; then
-            echo "File transfer failed: ${file}" | tee --append "${SUMMARY_FILE}"
-            # Set flag to notify
+            echo "File distribution failed: ${file}" | tee --append $SUMMARY_FILE
+
+            # Move file to campus NAS for long term storage
+            year=$(echo ${file} | cut --characters 1-4)
+            month=$(echo ${file} | cut --characters 5-6)
+            nas_site_dir="${NAS_DIR}/${RADAR_ID}_rawacf_dmap/${year}/${month}/"
+            mkdir --parents $nas_site_dir
+            mv --verbose $file $nas_site_dir
         else
-            echo "File distributed successfully: ${file}"
+            echo "File distribution successful: ${file}" | tee --append $SUMMARY_FILE
         fi
 done
 
 
+# Iterate over all array files and back them up to NAS
 if [[ -n $array_files ]]; then
-    echo "Distributing the following dmap files" 
+    printf "\nDistributing the following array files:\n" 
     printf '%s\n' "${array_files[@]}"
 else
-    echo "No dmap files found to be transferred."
+    printf "\nNo array files found to be transferred.\n"
 fi
 
-# Iterate over all array files and back them up to NAS
 for file in $array_files; do
-    h5stat "${file}" >& /dev/null
+    h5stat $file >& /dev/null
     if [[ $? -ne 0 ]]; then
-        echo "Array file failed h5stat test: ${file}" | tee --append "${SUMMARY_FILE}"
-        # TODO: Set a flag to notify
+        printf "\nArray file failed h5stat test: ${file}\n" | tee --append $SUMMARY_FILE
     else
-        echo "\nDistributing ${file}"
+        printf "\nDistributing ${file}\n"
         chmod --verbose 664 "${file}"
 
         # TODO: Do we want to do rsync here instead?
@@ -142,15 +175,25 @@ for file in $array_files; do
 
         # TODO: array files aren't synced to mirror - do we still want to back them up in the holding directory?
 
-        year=$(echo ${file} | cut -c 1-4)
-        month=$(echo ${file} | cut -c 5-6)
+        year=$(echo ${file} | cut --characters 1-4)
+        month=$(echo ${file} | cut --characters 5-6)
         nas_site_dir="${NAS_DIR}/${RADAR_ID}_rawacf/${year}/${month}/"
-        mkdir --parents "${nas_site_dir}"
-        mv --verbose "${file}" "${nas_site_dir}"
+        mkdir --parents $nas_site_dir
+        mv --verbose $file $nas_site_dir
+        printf "File distribution successful: ${file}\n" | tee --append $SUMMARY_FILE
     fi
 done
 
-# TODO: Handle flags for inotify here
+# TODO: Send error file to Engineering dashboard
+printf "\nTriggering next script via inotify...\n"
+# Remove "flag" sent by convert_and_restructure to reset flag
+# and allow inotify to see the next flag sent in
+rm --verbose $FLAG_IN
 
-# TODO: Send notification if errors occur
-printf "Finished distributing data. End time: $(date -u)\n\n\n"
+# Send out "flag" to trigger next script with inotify
+touch $FLAG_OUT
+rsync -av --rsh=ssh $FLAG_OUT $FLAG_DEST
+
+printf "\nFinished file conversion. End time: $(date --utc "+%Y%m%d %H:%M:%S UTC")\n\n" | tee --append $SUMMARY_FILE
+
+exit
