Several modifications per Theo's review.
* rsync_to_nas puts files directly into the correct NAS directory - no more use for daily/ directory
* convert_and_restructure script removed, all conversion will be done on campus or not required.
* CONVERT_ON_CAMPUS list removed, convert_on_campus script will convert any HDF5 files it encounters. DMAP files will not be put in the [site]_holding_dir, they will go straight to the [site]_data dir on campus.

diff --git a/borealis/rsync_to_nas b/borealis/rsync_to_nas
--- a/borealis/rsync_to_nas
+++ b/borealis/rsync_to_nas
@@ -51,7 +51,10 @@ else
 	readonly DEST="/data/borealis_data" # On Site Linux
 fi
 
-readonly SUCCESS_DEST="${DEST}/daily/" # All good Borealis files go here
+readonly ANTENNAS_IQ_DEST="${DATA_DIR}/antennas_iq_array"
+readonly RAWACF_DMAP_DEST="${DATA_DIR}/rawacf_dmap"
+readonly RAWACF_ARRAY_DEST="${DATA_DIR}/rawacf_array"
+readonly BACKUP_DEST="${DATA_DIR}/backup"
 readonly FAIL_DEST="${DEST}/conversion_failure/" # Any files that fail checks go here
 
 # Create log file. New file created daily
@@ -99,9 +102,11 @@ printf "Transferring from: $SOURCE\n" | tee --append $SUMMARY_FILE
 if [[ " ${NAS_SITES[*]} " =~ " ${RADAR_ID} " ]]; then
 	printf "Transferring to NAS: $DEST\n\n" | tee --append $SUMMARY_FILE
 	search=(\( -name "*rawacf*" -o -name "*bfiq*" -o -name "*antennas_iq*" \))
+	readonly TRANSFER_LOC=""
 else
 	printf "Transferring to Site-Linux: $DEST\n\n" | tee --append $SUMMARY_FILE
 	search=(\( -name "*rawacf*" \)) 	# If transferring to site computer, only send rawacf
+	readonly TRANSFER_LOC="$SITE_LINUX:"
 fi
 
 # Using the filename that this script triggered on, a pattern can be determined to omit the current
@@ -130,12 +135,27 @@ fi
 # Transfer files
 for file in $files
 do
-	printf "\nSynching: $file\n"
+	printf "\nSyncing: $file\n"
 	
 	# Ensure that the file has all group permissions enabled (read/write/execute)
 	chmod --verbose 775 $file
 
-	SPECIFIC_DEST="$SUCCESS_DEST"
+  needs_zip=0
+  backup=0
+  if [[ $file == "*.rawacf" ]]; then
+	  SPECIFIC_DEST="$RAWACF_DMAP_DEST"
+	  needs_zip=1  # bzip rawacf DMAP files
+	  backup=1  # backup rawacf files
+	elif [[ $file == "*.rawacf.h5" ]]; then
+	  SPECIFIC_DEST="$RAWACF_ARRAY_DEST"
+	  backup=1  # backup rawacf files
+	elif [[ $file == "*.antennas_iq.h5" ]]; then
+	  SPECIFIC_DEST="$ANTENNAS_IQ_DEST"
+	else
+	  error="unknown file type: ${file}\n"
+	  printf "${error}" | tee --append $SUMMARY_FILE
+	  SPECIFIC_DEST="$FAIL_DEST"
+	fi
 
 	# Check that the timestamps and file modification times are consistent. If they aren't, change
 	# the destination to the failed file directory.
@@ -150,30 +170,39 @@ do
 		SPECIFIC_DEST="$FAIL_DEST"	# Change destination
 	fi
 
+  # Bzip file if needed
+  if [[ $needs_zip -eq 1 ]]; then
+    file_to_transfer="${file}.bz2"
+    bzip2 --verbose $file
+  else
+    file_to_transfer="$file"
+  fi
+
+  if [[ $backup -eq 1 ] && [ " ${NAS_SITES[*]} " =~ " ${RADAR_ID} " ]]; then
+    # rsync file to NAS for backup
+    rsync -av --append-verify --timeout=180 --rsh=ssh $file_to_transfer "${TRANSFER_LOC}${BACKUP_DEST}"
+
+    # Check if transfer was okay using the md5sum program
+    verify_transfer $file_to_transfer "${BACKUP_DEST}/$(basename $file_to_transfer)" ${TRANSFER_LOC%:}
+    return_value=$?
+  fi
+
 	printf "Destination: $SPECIFIC_DEST\n"
-	if [[ " ${NAS_SITES[*]} " =~ " ${RADAR_ID} " ]]; then
-		# rsync file to NAS
-		rsync -av --append-verify --timeout=180 --rsh=ssh $file $SPECIFIC_DEST
+	# rsync file to NAS or site-linux computer
+  rsync -av --append-verify --timeout=180 --rsh=ssh $file_to_transfer "${TRANSFER_LOC}${SPECIFIC_DEST}"
 
-		# Check if transfer was okay using the md5sum program
-		verify_transfer $file "${SPECIFIC_DEST}/$(basename $file)"
-		return_value=$?
-	else
-		# rsync file to site computer
-		rsync -av --append-verify --timeout=180 --rsh=ssh $file $SITE_LINUX:$SPECIFIC_DEST
-
-		verify_transfer $file "${SPECIFIC_DEST}/$(basename $file)" $SITE_LINUX
-		return_value=$?
-	fi
+  # Check if transfer was okay using the md5sum program
+  verify_transfer $file_to_transfer "${SPECIFIC_DEST}/$(basename $file_to_transfer)" ${TRANSFER_LOC%:}
+  return_value=$?
 
 	if [[ $return_value -eq 0 ]]; then
 		# Remove the file if transfer is successful
-		printf "Successfully transferred: ${file}\n" | tee --append $SUMMARY_FILE
+		printf "Successfully transferred: ${file_to_transfer}\n" | tee --append $SUMMARY_FILE
 		printf "Deleting file...\n"
-		rm --verbose $file
+		rm --verbose $file_to_transfer
 	else
 		# If file not transferred successfully, don't delete and try again next time
-		printf "Transfer failed: ${file}\n" | tee --append $SUMMARY_FILE
+		printf "Transfer failed: ${file_to_transfer}\n" | tee --append $SUMMARY_FILE
 		printf "File not deleted.\n"
 	fi
 done
diff --git a/site-linux/rsync_to_campus b/site-linux/rsync_to_campus
--- a/site-linux/rsync_to_campus
+++ b/site-linux/rsync_to_campus
@@ -35,12 +35,8 @@ readonly BOREALIS_SOURCE="${DATA_DIR}/rawacf_array/"
 readonly IQPLOT_SOURCE="${HOME}/logs/daily_plots/"
 
 # If site isn't transferring dmap files, send to holding directory for campus conversion
-if [[ " ${CONVERT_ON_CAMPUS_SITES[*]} " =~ " ${RADAR_ID} " ]]; then
-	readonly DEST="/sddata/${RADAR_ID}_holding_dir"
-else
-	readonly DEST="/sddata/${RADAR_ID}_data/"
-fi
-
+readonly HDF5_DEST="/sddata/${RADAR_ID}_holding_dir"
+readonly DMAP_DEST="/sddata/${RADAR_ID}_data/"
 readonly PLOTDEST="/home/dataman/antennas_iq_plots/${RADAR_ID}_iq_plots/"
 
 # Create log file. New file created daily
@@ -77,48 +73,44 @@ printf "pyDARNio: $(git -C ${HOME}/pyDARNio status | grep "On branch"), last com
 		$(git -C ${HOME}/pyDARNio log -1 --format="%h %cd" --date=iso)\n" | tee --append $SUMMARY_FILE
 
 printf "Transferring from: $DATA_DIR\n" | tee --append $SUMMARY_FILE
-printf "Transferring to: $SDCOPY:$DEST\n\n" | tee --append $SUMMARY_FILE
+printf "Transferring HDF5 files to: $SDCOPY:$HDF5_DEST\n\n" | tee --append $SUMMARY_FILE
+printf "Transferring dmap files to: $SDCOPY:$DMAP_DEST\n\n" | tee --append $SUMMARY_FILE
 
-# Check if this site is transferring dmaps to campus
-if [[ ! " ${CONVERT_ON_CAMPUS_SITES[*]} " =~ " ${RADAR_ID} " ]]; then
-	# Find all dmap files to transfer
-	files=$(find ${DMAP_SOURCE} -name '*rawacf.bz2' -printf '%p\n')
+# Find all dmap files to transfer
+files=$(find ${DMAP_SOURCE} -name '*rawacf.bz2' -printf '%p\n')
 
-	if [[ -n $files ]]; then
-		printf "\nPlacing following dmap files in ${SDCOPY}:${DEST}:\n"
-		printf '%s\n' "${files[@]}"
-	else
-		printf "No dmap files found to be transferred.\n" | tee --append $SUMMARY_FILE
-	fi
-
-	# Transfer all files found
-	for file in $files; do
-		printf "\nTransferring: ${file} to ${SDCOPY}:${DEST}\n"
-		rsync -av --append-verify --timeout=180 --rsh=ssh $file $SDCOPY:$DEST
-
-		# Check if transfer was okay using the md5sum program, then remove the file if it matches
-		verify_transfer $file "${DEST}/$(basename $file)" $SDCOPY
-		return_value=$?
-		if [[ $return_value -eq 0 ]]; then
-			printf "Successfully transferred: ${file}\n" | tee --append $SUMMARY_FILE
-			printf "Deleting file...\n"
-			rm --verbose $file
-		else
-            # If file not transferred successfully, don't delete and try again next time
-			printf "Transfer failed: ${file}\n" | tee --append $SUMMARY_FILE
-			printf "File not deleted.\n"
-		fi
-	done
+if [[ -n $files ]]; then
+  printf "\nPlacing following dmap files in ${SDCOPY}:${DMAP_DEST}:\n"
+  printf '%s\n' "${files[@]}"
 else
-	printf "Not transferring any dmap files\n" | tee --append $SUMMARY_FILE
+  printf "No dmap files found to be transferred.\n" | tee --append $SUMMARY_FILE
 fi
+
+# Transfer all files found
+for file in $files; do
+  printf "\nTransferring: ${file} to ${SDCOPY}:${DMAP_DEST}\n"
+  rsync -av --append-verify --timeout=180 --rsh=ssh $file $SDCOPY:$DMAP_DEST
+
+  # Check if transfer was okay using the md5sum program, then remove the file if it matches
+  verify_transfer $file "${DMAP_DEST}/$(basename $file)" $SDCOPY
+  return_value=$?
+  if [[ $return_value -eq 0 ]]; then
+    printf "Successfully transferred: ${file}\n" | tee --append $SUMMARY_FILE
+    printf "Deleting file...\n"
+    rm --verbose $file
+  else
+          # If file not transferred successfully, don't delete and try again next time
+    printf "Transfer failed: ${file}\n" | tee --append $SUMMARY_FILE
+    printf "File not deleted.\n"
+  fi
+done
 
 
 # Find all hdf5 files to transfer
 files=$(find ${BOREALIS_SOURCE} -name '*rawacf.h5' -printf '%p\n')
 
 if [[ -n $files ]]; then
-	printf "\n\nPlacing following hdf5 files in ${SDCOPY}:${DEST}:\n"
+	printf "\n\nPlacing following hdf5 files in ${SDCOPY}:${HDF5_DEST}:\n"
 	printf '%s\n' "${files[@]}"
 else
 	printf "\nNo hdf5 files found to be transferred.\n" | tee --append $SUMMARY_FILE
@@ -127,10 +119,10 @@ fi
 # Transfer all files found
 for file in $files; do
 	printf "\nTransferring: $(basename $file)\n"
-	rsync -av --append-verify --timeout=180 --rsh=ssh $file $SDCOPY:$DEST
+	rsync -av --append-verify --timeout=180 --rsh=ssh $file $SDCOPY:$HDF5_DEST
 
 	# Check if transfer was okay using the md5sum program
-	verify_transfer $file "${DEST}/$(basename $file)" $SDCOPY
+	verify_transfer $file "${HDF5_DEST}/$(basename $file)" $SDCOPY
 	return_value=$?
 	if [[ $return_value -eq 0 ]]; then
 		printf "Successfully transferred: ${file}\n" | tee --append $SUMMARY_FILE
