Updated code based on Kevin's code review
- Fixed antennas_iq backlog to use config.sh
- Moved check for multiple instances of script before exec command to direct output to logs
- Changed strings to fstrings for older python scripts
- Other small changes

diff --git a/borealis/rsync_to_nas b/borealis/rsync_to_nas
--- a/borealis/rsync_to_nas
+++ b/borealis/rsync_to_nas
@@ -56,10 +56,10 @@ else
 fi
 
 # Create log file. New file created daily
-readonly LOGGING_DIR="${HOME}/logs/rsync_to_nas/$(date +%Y)/$(date +%m)"
+readonly LOGGING_DIR="${HOME}/logs/rsync_to_nas/$(date +%Y/%m)"
 mkdir --parents $LOGGING_DIR
 readonly LOGFILE="${LOGGING_DIR}/$(date +%Y%m%d).rsync_to_nas.log"
-readonly SUMMARY_DIR="${HOME}/logs/rsync_to_nas/summary/$(date +%Y)/$(date +%m)"
+readonly SUMMARY_DIR="${HOME}/logs/rsync_to_nas/summary/$(date +%Y/%m)"
 mkdir --parents $SUMMARY_DIR
 readonly SUMMARY_FILE="${SUMMARY_DIR}/$(date -u +%Y%m%d).rsync_to_nas_summary.log"
 
@@ -68,6 +68,12 @@ readonly TELEMETRY_SCRIPT_DIR="${TELEMETRY_DIR}/${RADARID}/rsync_to_nas"
 
 ###################################################################################################
 
+# Ensure that only a single instance of this script runs.
+if pidof -o %PPID -x -- "$(basename -- $0)" > /dev/null; then
+	printf "Error: Script $0 is already running. Exiting...\n"
+	exit 1
+fi
+
 exec &>> $LOGFILE # Redirect STDOUT and STDERR to $LOGFILE
 
 printf "################################################################################\n\n" | tee --append $SUMMARY_FILE
@@ -75,12 +81,6 @@ printf "########################################################################
 # Date in UTC format for logging
 printf "Executing $0 on $(hostname) for ${RADARID}\n" | tee --append $SUMMARY_FILE
 date --utc "+%Y%m%d %H:%M:%S UTC" | tee --append $SUMMARY_FILE
-
-# Ensure that only a single instance of this script runs.
-if pidof -o %PPID -x -- "$(basename -- $0)" > /dev/null; then
-	printf "Error: Script $0 is already running. Exiting...\n"
-	exit 1
-fi
 
 # Get status info on data_flow and pyDARNio repos
 printf "data_flow: $(git -C ${HOME}/data_flow status | grep "On branch"), last commit: \
diff --git a/site-linux/antennas_iq_backlog b/site-linux/antennas_iq_backlog
--- a/site-linux/antennas_iq_backlog
+++ b/site-linux/antennas_iq_backlog
@@ -14,7 +14,8 @@
 
 ###################################################################################################
 
-source "${HOME}/.bashrc" # source the RADARID, SDCOPY and other things
+source "${HOME}/.bashrc"    # source the RADARID, SDCOPY and other things
+source "${HOME}/data_flow/config.sh"  # Load common data flow variables
 source "${HOME}/data_flow/library/data_flow_functions.sh" # Load in function library
 source "${HOME}/pydarnio-env/bin/activate"
 
@@ -25,10 +26,6 @@ readonly DATA_DIR="/borealis_nfs/borealis_data"
 readonly SOURCE="${DATA_DIR}/antennas_iq_array" # this is the source
 readonly PROBLEM_FILES_DEST="${DATA_DIR}/conversion_failure"
 
-# Specify which sites will convert each file type
-readonly ANTENNAS_IQ_SITES=("sas" "pgr" "inv" "cly" "rkn")
-readonly LOW_MEMORY_SITES=("pgr" "inv" "rkn")
-
 # Create log file. New file created daily
 readonly LOGGING_DIR="${HOME}/logs"
 mkdir --parents $LOGGING_DIR
@@ -37,19 +34,18 @@ readonly SUMMARY_FILE="${LOGGING_DIR}/antennas_iq_backlog_summary.log"
 
 ###################################################################################################
 
-# Redirect all stdout and sterr in this script to $LOGFILE
+# Ensure that only a single instance of this script runs.
+if pidof -o %PPID -x -- "$(basename -- $0)" > /dev/null; then
+	printf "Error: Script $0 is already running. Exiting...\n"
+	exit 1
+fi
+
 exec &>> $LOGFILE # Redirect STDOUT and STDERR to $LOGFILE
 
 printf "################################################################################\n\n" | tee --append $SUMMARY_FILE
 
 printf "Executing $0 on $(hostname)\n" | tee --append $SUMMARY_FILE
 date --utc "+%Y%m%d %H:%M:%S UTC" | tee --append $SUMMARY_FILE
-
-# Ensure that only a single instance of this script runs.
-if pidof -o %PPID -x -- "$(basename -- $0)" > /dev/null; then
-	printf "Error: Script $0 is already running. Exiting...\n"
-	exit 1
-fi
 
 # Get status info on data_flow and pyDARNio repos
 printf "data_flow repo: $(git -C ${HOME}/data_flow status | grep "On branch"), last commit: \
diff --git a/site-linux/convert_and_restructure b/site-linux/convert_and_restructure
--- a/site-linux/convert_and_restructure
+++ b/site-linux/convert_and_restructure
@@ -44,10 +44,10 @@ readonly BACKUP_DEST="${DATA_DIR}/backup"
 readonly PROBLEM_FILES_DEST="${DATA_DIR}/conversion_failure"
 
 # Create log file. New file created daily
-readonly LOGGING_DIR="${HOME}/logs/convert_and_restructure/$(date +%Y)/$(date +%m)"
+readonly LOGGING_DIR="${HOME}/logs/convert_and_restructure/$(date +%Y/%m)"
 mkdir --parents $LOGGING_DIR
 readonly LOGFILE="${LOGGING_DIR}/$(date +%Y%m%d).convert_and_restructure.log"
-readonly  SUMMARY_DIR="${HOME}/logs/convert_and_restructure/summary/$(date +%Y)/$(date +%m)"
+readonly  SUMMARY_DIR="${HOME}/logs/convert_and_restructure/summary/$(date +%Y/%m)"
 mkdir --parents $SUMMARY_DIR
 readonly SUMMARY_FILE="${SUMMARY_DIR}/$(date -u +%Y%m%d).convert_and_restructure_summary.log"
 
@@ -56,19 +56,18 @@ readonly TELEMETRY_SCRIPT_DIR="${TELEMETRY_DIR}/${RADARID}/convert_and_restructu
 
 ###################################################################################################
 
-# Redirect all stdout and sterr in this script to $LOGFILE
+# Ensure that only a single instance of this script runs.
+if pidof -o %PPID -x -- "$(basename -- $0)" > /dev/null; then
+	printf "Error: Script $0 is already running. Exiting...\n"
+	exit 1
+fi
+
 exec &>> $LOGFILE # Redirect STDOUT and STDERR to $LOGFILE
 
 printf "################################################################################\n\n" | tee --append $SUMMARY_FILE
 
 printf "Executing $0 on $(hostname) for ${RADARID}\n" | tee --append $SUMMARY_FILE
 date --utc "+%Y%m%d %H:%M:%S UTC" | tee --append $SUMMARY_FILE
-
-# Ensure that only a single instance of this script runs.
-if pidof -o %PPID -x -- "$(basename -- $0)" > /dev/null; then
-	printf "Error: Script $0 is already running. Exiting...\n"
-	exit 1
-fi
 
 # Get status info on data_flow and pyDARNio repos
 printf "data_flow: $(git -C ${HOME}/data_flow status | grep "On branch"), last commit: \
