Changed whitespace tabs to be consistent for bash scripts

diff --git a/borealis/rsync_to_nas b/borealis/rsync_to_nas
--- a/borealis/rsync_to_nas
+++ b/borealis/rsync_to_nas
@@ -89,8 +89,8 @@ printf "data_flow: $(git -C ${HOME}/data_flow status | grep "On branch"), last c
 		$(git -C ${HOME}/data_flow log -1 --format="%h %cd" --date=iso)\n" | tee --append $SUMMARY_FILE
 
 if [[ -z "$SOURCE" ]]; then
-        printf "Error: Source directory not defined. Exiting...\n"
-        exit 1
+	printf "Error: Source directory not defined. Exiting...\n"
+	exit 1
 fi
 printf "Transferring from: $SOURCE\n" | tee --append $SUMMARY_FILE
 
@@ -140,21 +140,21 @@ do
 	# Ensure that the file has all group permissions enabled (read/write/execute)
 	chmod --verbose 775 $file
 
-  needs_zip=0
-  backup=0
-  if [[ $file == *.rawacf ]]; then
-	  SPECIFIC_DEST="$RAWACF_DMAP_DEST"
-	  needs_zip=1  # bzip rawacf DMAP files
-	  backup=1  # backup rawacf files
+	needs_zip=0
+	backup=0
+	if [[ $file == *.rawacf ]]; then
+		SPECIFIC_DEST="$RAWACF_DMAP_DEST"
+		needs_zip=1  # bzip rawacf DMAP files
+		backup=1  # backup rawacf files
 	elif [[ $file == *.rawacf.h5 ]]; then
-	  SPECIFIC_DEST="$RAWACF_ARRAY_DEST"
-	  backup=1  # backup rawacf files
+		SPECIFIC_DEST="$RAWACF_ARRAY_DEST"
+		backup=1  # backup rawacf files
 	elif [[ $file == *.antennas_iq.h5 ]]; then
-	  SPECIFIC_DEST="$ANTENNAS_IQ_DEST"
+		SPECIFIC_DEST="$ANTENNAS_IQ_DEST"
 	else
-	  error="unknown file type: ${file}\n"
-	  printf "${error}" | tee --append $SUMMARY_FILE
-	  SPECIFIC_DEST="$FAIL_DEST"
+		error="unknown file type: ${file}\n"
+		printf "${error}" | tee --append $SUMMARY_FILE
+		SPECIFIC_DEST="$FAIL_DEST"
 	fi
 
 	# Check that the timestamps and file modification times are consistent. If they aren't, change
@@ -170,32 +170,32 @@ do
 		SPECIFIC_DEST="$FAIL_DEST"	# Change destination
 	fi
 
-  # Bzip file if needed
-  if [[ $needs_zip -eq 1 ]]; then
-    printf "Bzipping $file to $file_to_transfer\n"
-    file_to_transfer="${file}.bz2"
-    bzip2 --verbose $file
-  else
-    file_to_transfer="$file"
-  fi
+	# Bzip file if needed
+	if [[ $needs_zip -eq 1 ]]; then
+		printf "Bzipping $file to $file_to_transfer\n"
+		file_to_transfer="${file}.bz2"
+		bzip2 --verbose $file
+	else
+		file_to_transfer="$file"
+	fi
 
-  if [[ $backup -eq 1 && " ${NAS_SITES[*]} " =~ " ${RADAR_ID} " ]]; then
-    # rsync file to NAS for backup
-    printf "Backing up to: $BACKUP_DEST\n"
-    rsync -av --append-verify --timeout=180 --rsh=ssh $file_to_transfer "${TRANSFER_LOC}${BACKUP_DEST}"
+	if [[ $backup -eq 1 && " ${NAS_SITES[*]} " =~ " ${RADAR_ID} " ]]; then
+		# rsync file to NAS for backup
+		printf "Backing up to: $BACKUP_DEST\n"
+		rsync -av --append-verify --timeout=180 --rsh=ssh $file_to_transfer "${TRANSFER_LOC}${BACKUP_DEST}"
 
-    # Check if transfer was okay using the md5sum program
-    verify_transfer $file_to_transfer "${BACKUP_DEST}/$(basename $file_to_transfer)" ${TRANSFER_LOC%:}
-    return_value=$?
-  fi
+		# Check if transfer was okay using the md5sum program
+		verify_transfer $file_to_transfer "${BACKUP_DEST}/$(basename $file_to_transfer)" ${TRANSFER_LOC%:}
+		return_value=$?
+	fi
 
 	printf "Transferring to: $SPECIFIC_DEST\n"
 	# rsync file to NAS or site-linux computer
-  rsync -av --append-verify --timeout=180 --rsh=ssh $file_to_transfer "${TRANSFER_LOC}${SPECIFIC_DEST}"
+	rsync -av --append-verify --timeout=180 --rsh=ssh $file_to_transfer "${TRANSFER_LOC}${SPECIFIC_DEST}"
 
-  # Check if transfer was okay using the md5sum program
-  verify_transfer $file_to_transfer "${SPECIFIC_DEST}/$(basename $file_to_transfer)" ${TRANSFER_LOC%:}
-  return_value=$?
+	# Check if transfer was okay using the md5sum program
+	verify_transfer $file_to_transfer "${SPECIFIC_DEST}/$(basename $file_to_transfer)" ${TRANSFER_LOC%:}
+	return_value=$?
 
 	if [[ $return_value -eq 0 ]]; then
 		# Remove the file if transfer is successful
diff --git a/site-linux/plot_antennas_iq b/site-linux/plot_antennas_iq
--- a/site-linux/plot_antennas_iq
+++ b/site-linux/plot_antennas_iq
@@ -105,40 +105,40 @@ else
 fi
 
 for f in ${daily_files}; do
-  printf "\nPlotting ${f}\n"
+	printf "\nPlotting ${f}\n"
 
-  python3 ${HOME}/data_flow/library/iq_plotting.py "${f}" --plot-directory=${FULLSIZE_DEST} --antennas="0-19" --min-power=30 --max-power=80
+	python3 ${HOME}/data_flow/library/iq_plotting.py "${f}" --plot-directory=${FULLSIZE_DEST} --antennas="0-19" --min-power=30 --max-power=80
 
-  if [ $? -eq 0 ]; then
-    printf "Successfully converted: ${f}\n" | tee --append $SUMMARY_FILE
-  else
-     error="Failed to generate iq plot from: ${f}\n"
-     printf "${error}" | tee --append $SUMMARY_FILE
+	if [ $? -eq 0 ]; then
+		printf "Successfully converted: ${f}\n" | tee --append $SUMMARY_FILE
+	else
+		error="Failed to generate iq plot from: ${f}\n"
+		printf "${error}" | tee --append $SUMMARY_FILE
 
-     message="$(date +'%Y%m%d %H:%M:%S')   ${RADAR_ID} - ${error}"
-     alert_slack "${message}" "${SLACK_DATAFLOW_WEBHOOK}"
-  fi
+		message="$(date +'%Y%m%d %H:%M:%S')   ${RADAR_ID} - ${error}"
+		alert_slack "${message}" "${SLACK_DATAFLOW_WEBHOOK}"
+	fi
 done
 
 # Only need to resize plots if there were files to make
 if [[ -n $daily_files ]]; then
-  # Get the names of all plots just generated
-  daily_plots=$(ls ${FULLSIZE_DEST}/*.{png,jpg})
-  if [[ -z $daily_plots ]]; then
-    printf "Unable to find files to resize...\n" | tee --append $SUMMARY_FILE
-  fi
+	# Get the names of all plots just generated
+	daily_plots=$(ls ${FULLSIZE_DEST}/*.{png,jpg})
+	if [[ -z $daily_plots ]]; then
+		printf "Unable to find files to resize...\n" | tee --append $SUMMARY_FILE
+	fi
 
-  # Resize the images to a desired pixel width
-  for img in ${daily_plots}; do
-    printf "Resizing file: ${f}\n" | tee --append $SUMMARY_FILE
-	  smartresize ${img} 1000 ${PLOT_DEST}
-	  if [ $? -eq 0 ]; then
-	    rm --verbose ${img}
-	  else
-	    printf "Failed to resize ${img}"
-	    mv --verbose ${img} ${FAILED_RESIZE_DEST}
-    fi
-  done
+	# Resize the images to a desired pixel width
+	for img in ${daily_plots}; do
+		printf "Resizing file: ${f}\n" | tee --append $SUMMARY_FILE
+		smartresize ${img} 1000 ${PLOT_DEST}
+		if [ $? -eq 0 ]; then
+			rm --verbose ${img}
+		else
+			printf "Failed to resize ${img}"
+			mv --verbose ${img} ${FAILED_RESIZE_DEST}
+		fi
+	done
 fi
 
 printf "\nFinished $(basename $0). End time: $(date --utc "+%Y%m%d %H:%M:%S UTC")\n\n" | tee --append $SUMMARY_FILE
diff --git a/site-linux/rsync_to_campus b/site-linux/rsync_to_campus
--- a/site-linux/rsync_to_campus
+++ b/site-linux/rsync_to_campus
@@ -100,29 +100,29 @@ fi
 files=$(find ${DMAP_SOURCE} -name '*rawacf.bz2' -printf '%p\n')
 
 if [[ -n $files ]]; then
-  printf "\nPlacing following dmap files in ${SDCOPY}:${DMAP_DEST}:\n"
-  printf '%s\n' "${files[@]}"
+	printf "\nPlacing following dmap files in ${SDCOPY}:${DMAP_DEST}:\n"
+	printf '%s\n' "${files[@]}"
 else
-  printf "No dmap files found to be transferred.\n" | tee --append $SUMMARY_FILE
+	printf "No dmap files found to be transferred.\n" | tee --append $SUMMARY_FILE
 fi
 
 # Transfer all files found
 for file in $files; do
-  printf "\nTransferring: ${file} to ${SDCOPY}:${DMAP_DEST}\n"
-  rsync -av --append-verify --timeout=180 --rsh=ssh $file $SDCOPY:$DMAP_DEST
+	printf "\nTransferring: ${file} to ${SDCOPY}:${DMAP_DEST}\n"
+	rsync -av --append-verify --timeout=180 --rsh=ssh $file $SDCOPY:$DMAP_DEST
 
-  # Check if transfer was okay using the md5sum program, then remove the file if it matches
-  verify_transfer $file "${DMAP_DEST}/$(basename $file)" $SDCOPY
-  return_value=$?
-  if [[ $return_value -eq 0 ]]; then
-    printf "Successfully transferred: ${file}\n" | tee --append $SUMMARY_FILE
-    printf "Deleting file...\n"
-    rm --verbose $file
-  else
-          # If file not transferred successfully, don't delete and try again next time
-    printf "Transfer failed: ${file}\n" | tee --append $SUMMARY_FILE
-    printf "File not deleted.\n"
-  fi
+	# Check if transfer was okay using the md5sum program, then remove the file if it matches
+	verify_transfer $file "${DMAP_DEST}/$(basename $file)" $SDCOPY
+	return_value=$?
+	if [[ $return_value -eq 0 ]]; then
+		printf "Successfully transferred: ${file}\n" | tee --append $SUMMARY_FILE
+		printf "Deleting file...\n"
+		rm --verbose $file
+	else
+			# If file not transferred successfully, don't delete and try again next time
+		printf "Transfer failed: ${file}\n" | tee --append $SUMMARY_FILE
+		printf "File not deleted.\n"
+	fi
 done
 
 
@@ -167,21 +167,21 @@ else
 fi
 
 for file in $files; do
-  printf "\nTransferring: ${file}\n"
-  rsync -av --append-verify --timeout=180 --rsh=ssh ${file} $SDCOPY:$PLOT_DEST
+	printf "\nTransferring: ${file}\n"
+	rsync -av --append-verify --timeout=180 --rsh=ssh ${file} $SDCOPY:$PLOT_DEST
 
-  # Check if transfer was okay using the md5sum program
-  verify_transfer $file "${PLOT_DEST}/$(basename $file)" $SDCOPY
-  return_value=$?
-  if [[ $return_value -eq 0 ]]; then
-    printf "Successfully transferred: ${file}\n" | tee --append $SUMMARY_FILE
-    printf "Deleting file...\n"
-    rm --verbose ${file}
-  else
-    # If file not transferred successfully, try again next time, don't delete
-    printf "Transfer failed: ${file}\n" | tee --append $SUMMARY_FILE
-    printf "File not deleted.\n"
-  fi
+	# Check if transfer was okay using the md5sum program
+	verify_transfer $file "${PLOT_DEST}/$(basename $file)" $SDCOPY
+	return_value=$?
+	if [[ $return_value -eq 0 ]]; then
+		printf "Successfully transferred: ${file}\n" | tee --append $SUMMARY_FILE
+		printf "Deleting file...\n"
+		rm --verbose ${file}
+	else
+		# If file not transferred successfully, try again next time, don't delete
+		printf "Transfer failed: ${file}\n" | tee --append $SUMMARY_FILE
+		printf "File not deleted.\n"
+	fi
 done
 
 printf "\nFinished $(basename $0). End time: $(date --utc "+%Y%m%d %H:%M:%S UTC")\n\n" | tee --append $SUMMARY_FILE
